F = -1
LIBS = F:\Projects\cpp\estrutura-de-dados\utils
build:
ifneq ($(F), -1)
	g++ \
	$(LIBS)/*.h \
	$(F).cpp \
	-o \
	$(F)
else
	echo "Digite um nome de arquivo valido para compilacao!"
endif
run:
	$(F).exe
come:
	make build run